FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++ libc6-compat

COPY package*.json ./

RUN npm ci

COPY prisma ./prisma/
COPY prisma.config.ts ./

RUN npm run prisma:generate

COPY . .

EXPOSE 8001

CMD ["sh", "-c", "npm run prisma:migrate && npm run start:dev"]

